### PR TITLE
Splitting gulp file tasks into individual files for better maintainability

### PR DESCRIPTION
**Pull request by rsumilang**
I split up the gulp tasks into individual files in a directory called "gulpfile.js". The build system works exactly like before but now it should be easier to maintain tasks to the system.

### CODE REVIEW

**Comment by thejameskyle** [comment]
No thanks https://github.com/thejameskyle/marionette-wires/pull/44#issuecomment-83734146

**Comment by rsumilang** [comment]
Is there any reason?

**Comment by thejameskyle** [comment]
I would ask the inverse. Is there any reason to split it up into separate files?

You mentioned it was easier to maintain but that's not compelling. 

Splitting tasks up into individual files does not inherently make them easier to maintain.

**Comment by rsumilang** [comment]
@thejameskyle - I'll elaborate how it makes the code more maintainable:

1) The `reporter` variable [here](https://github.com/thejameskyle/marionette-wires/blob/master/gulpfile.js#L112) serves no value. This was easy to catch in my IDE because the variable was never used when defined.

https://github.com/thejameskyle/marionette-wires/blob/2946586e6386c5055fd7850c37d5adbefb5a3ee7/gulpfile.js/tasks/watch.js


2) The `api` variable gets set on [line 14](https://github.com/thejameskyle/marionette-wires/blob/master/gulpfile.js#L14) but never gets used until [line 107](https://github.com/thejameskyle/marionette-wires/blob/master/gulpfile.js#L107). A task and it's requirements are easier to identify in smaller sets of code.

Again, same example: https://github.com/thejameskyle/marionette-wires/blob/2946586e6386c5055fd7850c37d5adbefb5a3ee7/gulpfile.js/tasks/watch.js


3) I put the `bundle` function in it's own library. This makes it super clear which function I'm supposed to use because its exported and that's all I have access to. On that note, there is a bug on [line 113](https://github.com/thejameskyle/marionette-wires/blob/master/gulpfile.js#L113) because it should be using `bundle()`, not `bundler()`. Yeah I know, that's completely my fault ;D, but as you see, that's was hard to catch during code review (pull request).

https://github.com/thejameskyle/marionette-wires/blob/2946586e6386c5055fd7850c37d5adbefb5a3ee7/gulpfile.js/lib/bundler.js


4) Putting each individual task in it's own file in the [gulpfile.js/tasks](https://github.com/thejameskyle/marionette-wires/tree/2946586e6386c5055fd7850c37d5adbefb5a3ee7/gulpfile.js/tasks) directory adds the benefit of making it easy to read all the tasks in a project. I work across multiple projects and it's a nice added benefit to share needed tasks amongst projects by selecting task files I want and just copying them over. I think people can benefit from this.

**Comment by thejameskyle** [comment]
> 1) The reporter variable here serves no value. This was easy to catch in my IDE because the variable was never used when defined.

It's used right here: https://github.com/thejameskyle/marionette-wires/blob/master/gulpfile.js#L86

> 2) The api variable gets set on line 14 but never gets used until line 107. A task and it's requirements are easier to identify in smaller sets of code.

Dependencies should always be listed first. 

> 3) I put the bundle function in it's own library. This makes it super clear which function I'm supposed to use because its exported and that's all I have access to. On that note, there is a bug on line 113 because it should be using bundle(), not bundler(). Yeah I know, that's completely my fault ;D, but as you see, that's was hard to catch during code review (pull request).

Maybe bundler isn't the best name, but there's two functions in the entire file that aren't tasks. That doesn't seem like a maintenance nightmare by any extent of the imagination.

> 4) Putting each individual task in it's own file in the gulpfile.js/tasks directory adds the benefit of making it easy to read all the tasks in a project. I work across multiple projects and it's a nice added benefit to share needed tasks amongst projects by selecting task files I want and just copying them over. I think people can benefit from this.

Still not compelling.

Ultimately if it works for you then fine go do it, but this is a very opinionated project which also needs to be accessible. Making the build system unnecessarily complex and inconsistent with every other project that uses gulp is not something I'm going to do.

**Comment by rsumilang** [comment]
I know where the reporter variable is used but it makes no sense to set it again later to "dot". I don't see how splitting up the files makes it complex but only easier. Check out this (gulp starter)[https://github.com/greypants/gulp-starter/tree/2.0] project. Thanks for your reply :)

**Pull request closed without merging**
