### PR TITLE
Add Storage

### PR DESCRIPTION
**Pull request by thejameskyle**
Ping @jmeas @megawac @cmaher @samccone @jasonLaster 

This is a starting point for what I want to do.

You create a new `Storage` by doing:

```js
var ColorsStorage = Storage.extend({
  model: Model,
  collection: Collection
});

var storage = new ColorsStorage();
```

The main apis seen here are the `find`, `findAll`, and `save`:

```js
fetch(id) {
  return storage.find(id).then(model => {
    this.model = model;
  });
}
```

```js
fetch() {
  return storage.findAll().then(collection => {
    this.collection = collection;
  });
}
```

```js
onSubmit() {
  this.model.set(this.formData);
  storage.save(this.model).then(() => {
    // ...
  });
}
```

I also want to add some hooks for using local storage or whatever you want.

### CODE REVIEW

**Comment by megawac** [comment]
> I also want to add some hooks for using local storage or whatever you want.

Maybe just a `localForage` interface?

**Comment by thejameskyle** [comment]
@megawac yup, I just want two methods that will be called on get/set.

**Comment by thejameskyle** [comment]
I'm going to merge this so I can do other things, feel free to make an comments.

**Comment by cmaher** [comment]
I just did [something extremely similar](https://github.com/cmaher/capacitor/blob/master/lib/store.js) in capacitor, so I like the idea.

**Pull request merged**
